from django.urls import path
from .views import (
    AdminCourseFormDataView,
    AdminLessonFormDataView,
    AdminLessonsListView,
    AdminVideoFormDataView,
    AdminVideosListView,
    AdminMuxDirectUploadView,
    MuxWebhookView,
    AdminPurchasesListView,
    AdminPurchaseDetailView,
    AdminEnrollmentsListView,
    AdminEnrollmentDetailView,
    AdminEnrollmentToggleActiveView,
    AdminEnrollmentFormDataView,
    AdminCreateEnrollmentView,
    AdminUsersListView,
    AdminUserDetailView,
    AdminUserUpdateView,
    AdminUserToggleActiveView,
    AdminSecurityDevicesListView,
    AdminSecurityDeviceToggleActiveView,
    AdminSecuritySessionsListView,
    AdminSecuritySessionDeactivateView,
    AdminSecurityVideoSessionsListView,
    AdminSecurityVideoSessionDeactivateView,
    AdminOverviewView,
)

urlpatterns = [
    path(
        "course-form-data/",
        AdminCourseFormDataView.as_view(),
        name="admin-course-form-data",
    ),
    path(
        "lesson-form-data/",
        AdminLessonFormDataView.as_view(),
        name="admin-lesson-form-data",
    ),
    path(
        "lessons/",
        AdminLessonsListView.as_view(),
        name="admin-lessons-list",
    ),
    path(
    "video-form-data/",
    AdminVideoFormDataView.as_view(),
    name="admin-video-form-data",
    ),
    path(
        "videos/",
        AdminVideosListView.as_view(),
        name="admin-videos-list",
    ),
    path(
    "mux/direct-upload/",
    AdminMuxDirectUploadView.as_view(),
    name="admin-mux-direct-upload",
    ),
    path(
    "mux/webhook/",
    MuxWebhookView.as_view(),
    name="mux-webhook",
    ),
    path(
    "purchases/",
    AdminPurchasesListView.as_view(),
    name="admin-purchases-list",
    ),
    path(
        "purchases/<int:pk>/",
        AdminPurchaseDetailView.as_view(),
        name="admin-purchase-detail",
    ),
    path(
    "enrollments/",
    AdminEnrollmentsListView.as_view(),
    name="admin-enrollments-list",
    ),
    path(
        "enrollments/<int:pk>/",
        AdminEnrollmentDetailView.as_view(),
        name="admin-enrollment-detail",
    ),
    path(
        "enrollments/<int:pk>/toggle-active/",
        AdminEnrollmentToggleActiveView.as_view(),
        name="admin-enrollment-toggle-active",
    ),
    path(
    "enrollment-form-data/",
    AdminEnrollmentFormDataView.as_view(),
    name="admin-enrollment-form-data",
    ),
    path(
        "enrollments/create/",
        AdminCreateEnrollmentView.as_view(),
        name="admin-create-enrollment",
    ),
    path(
    "users/",
    AdminUsersListView.as_view(),
    name="admin-users-list",
    ),
    path(
        "users/<int:pk>/",
        AdminUserDetailView.as_view(),
        name="admin-user-detail",
    ),
    path(
        "users/<int:pk>/update/",
        AdminUserUpdateView.as_view(),
        name="admin-user-update",
    ),
    path(
        "users/<int:pk>/toggle-active/",
        AdminUserToggleActiveView.as_view(),
        name="admin-user-toggle-active",
    ),
    path(
    "security/devices/",
    AdminSecurityDevicesListView.as_view(),
    name="admin-security-devices",
    ),
    path(
        "security/devices/<int:pk>/toggle-active/",
        AdminSecurityDeviceToggleActiveView.as_view(),
        name="admin-security-device-toggle-active",
    ),
    path(
        "security/sessions/",
        AdminSecuritySessionsListView.as_view(),
        name="admin-security-sessions",
    ),
    path(
        "security/sessions/<int:pk>/deactivate/",
        AdminSecuritySessionDeactivateView.as_view(),
        name="admin-security-session-deactivate",
    ),
    path(
        "security/video-sessions/",
        AdminSecurityVideoSessionsListView.as_view(),
        name="admin-security-video-sessions",
    ),
    path(
        "security/video-sessions/<int:pk>/deactivate/",
        AdminSecurityVideoSessionDeactivateView.as_view(),
        name="admin-security-video-session-deactivate",
    ),
    path(
    "overview/",
    AdminOverviewView.as_view(),
    name="admin-overview",
    ),
]